version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/backend
    volumes:
      - ./uploads:/app/uploads
      - ./backend/data.json:/app/backend/data.json
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
